import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				{/* <h1 className={styles.title}>
					Hello
				</h1> */}
				<div className=''>
					<p>Hello, I'm Fabrice Geib, a French web integrator and front end developer</p>

					<p>I love to experiment interactivity</p>

					<p>My work consists of a healthy mix of useful interface libraries, pointless animations and minimalist games.</p>

					<p>Most of my projects are released open source so you can freely modify or improve on them.</p>
				</div>

				<h2>Q & A</h2>

				<p>
					Where are you based?<br />
					What are you working on?<br />
					Where have you worked?<br />
					Are you available for hire ?
				</p>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					<a href="/api/hello" className={styles.card}>
						<h2>Api - Hello &rarr;</h2>
						<p>Api pages on your Next.js site.</p>
					</a>

					<a href="/series" className={styles.card}>
						<h2>Series &rarr;</h2>
						<p>
							The list of series I watch. The list of series I watch. The list of series I watch.
						</p>
					</a>
				</div>
			</main >

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div >
	)
}
